import { Grid } from '@arco-design/web-react'
import '@arco-design/web-react/dist/css/arco.css'
import Head from 'next/head'
import { useState } from 'react'
import MainBody from '../components/dashboard/MainBody'
import SideBar from '../components/dashboard/SideBar'
const Row = Grid.Row
const Col = Grid.Col

export default function Home() {
  const [currentTab, setCurrentTab] = useState('DashBoard')
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Row>
          <Col
            style={{
              height: '100vh',
              background: '#ffffff',
              boxShadow: 'rgba(0, 0, 0, 0.1) 0px 4px 12px',
              position: 'sticky',
              top: 0,
            }}
            xs={5}
            sm={4}
            md={4}
          >
            <SideBar currentTab={currentTab} setCurrentTab={setCurrentTab} />
          </Col>
          <Col xs={19} sm={20} md={20}>
            <MainBody currentTab={currentTab} setCurrentTab={setCurrentTab} />
          </Col>
        </Row>
      </main>

      {/* <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Saif Newaz
        </a>
      </footer> */}
    </div>
  )
}
